# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Distribute iOS App'
  lane :distribute_app do
    if is_ci?
      create_keychain(
        name: ENV['MATCH_KEYCHAIN_NAME'],
        password: ENV['MATCH_KEYCHAIN_PASSWORD'],
        default_keychain: true,
        unlock: true,
        timeout: 1800,
        lock_when_sleeps: false
      )
    end
    match(
      readonly: is_ci,
      keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD']
    )
    update_project_provisioning(
      xcodeproj: "{Template}.xcodeproj",
      profile: ENV["sigh_{BUNDLE_IDENTIFIER}_development_profile-path"],
      code_signing_identity: ENV['CODE_SIGNING_IDENTITY']
    )
    build_app(
      scheme: "Sample",
      export_options: {
        method: "development"
      }
    )
    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID_IOS'],
      groups: "gotties",
      ipa_path: ENV['IPA_PATH'],
      release_notes: ENV['RELEASE_NOTE'],
      firebase_cli_path: "#{Dir.pwd}/../node_modules/firebase-tools/lib/bin/firebase.js",
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "Template")
    upload_to_testflight
  end
end
